### ISSUE TITLE
Repo doesn't have a license

### ISSUE THREAD

**Issue by ronaldsmartin** [PratikPramanik/spyhunter#1]
Can I sell this as my own work, @PratikPramanik? :trollface:

<details open>
<summary>Checklist</summary>

- [X] ``LICENSE`` ✅ Commit <a href='https://github.com/PratikPramanik/spyhunter/commit/495bf961e46c00a67b2992b53c137c49bc153e09'><code>495bf96</code></a>
- [X] `LICENSE` ✅ Sandbox ran successfully

![Flowchart](http://24.199.78.105:8082/public/ce6ce618c30cb378fb7d36bd8142c84af3d90744a7522b1b20308cbb11f44a43_1_flowchart.svg)
</details>

**Comment by PratikPramanik** [comment]
@ronaldsmartin This isssue has been fixed, please check if it has been done to your satisfaction.

**Comment by ronaldsmartin** [comment]
Great, thank you!
